### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by jdumas** [cyberark/cyberark-conjur-cli#264]
Hi, I am trying to use the python cli with [LDAP authentication](https://docs.conjur.org/latest/en/Content/Integrations/ldap/ldap-authn-configure-dev-env.htm), but this doesn't seem to be supported by the python api/cli? Is that a missing feature, or am I missing something obvious?

**Comment by InbalZilberman** [comment]
@jdumas thank you for reaching out. This feature is not supported by python api/cli. You are welcome to contribute!
More information and instructions for how to deploy a deployment environment and run project tests can be found in [CONTRIBUTING.md](https://github.com/cyberark/conjur-api-python3/blob/master/CONTRIBUTING.md).
