### ISSUE TITLE
CLI supports conjurrc backwards compatibility

### ISSUE THREAD

**Issue by sigalsax** [cyberark/cyberark-conjur-cli#309]
## Is your feature request related to a problem? Please describe.

The CLI utilizes the `.conjurrc` file to hold the connection details required to properly connect to the user's Conjur server. The conjurrc  defines the location of the server's certificate, the account defined on the Conjur server, and the Conjur endpoint url. The conjurrc resembles the following:
```
cert_file: ...
conjur_account: ...
conjur_url: ...
```

In the latest CLI release, we updated these field names to be the ones detailed above for better UX _without_ supporting backwards compatibility. In other words, if our users still use the previous conjurrc form, they will fail on commands  when using the new CLI without understanding why. Therefore we should support backwards compatibility by supporting both the older field names and the newer ones.

Adding backwards compatibility, would allow us to continue working with other in-house tooling that rely on the old conjurrc file format (summon for example).

## Describe the solution you would like

Support both older conjurrc field names and the new ones

## Describe alternatives you have considered

We could fail and ask them to re-init the CLI (`conjur init`), which would in effect overwrite the old conjurrc with the newest format. This would be a quick win

## Additional context

-

**Comment by szh** [comment]
Fixed in #413
