### ISSUE TITLE
netrc_path attribute no longer working

### ISSUE THREAD

**Issue by aconic-sb** [cyberark/cyberark-conjur-cli#320]
## Summary
One of **.conjurrc** file attributes is [netrc_path](https://github.com/cyberark/summon-conjur#:~:text=you%20can%20also%20specify%20its%20location%20in%20.conjurrc%27s%20field%20netrc_path). Now it seems to do nothing and the .netrc file is always saved in user's home directory.

## Steps to Reproduce
1. add `netrc_path: "/etc/conjur.identity"` to your **.conjurrc** file
2. log in to Conjur: `conjur login`
3. check if your credentials get saved in /etc/conjur.identity instead of $HOME/.netrc file

## Expected Results
No $HOME/.netrc file exists and my Conjur identity is saved to /etc/conjur.identity

## Actual Results (including error logs, if applicable)
HOME/.netrc file gets created containing my Conjur identity instead of file /etc/conjur.identity which does not exist

## Reproducible
   * [x] Always
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
Latest version of the Python implementation of Conjur CLI (v7.0.1)

## Additional Information
I supposed this implementation of Conjur CLI should have kept the core functionality of the docker one (Ruby based) that is why I am reporting it as a bug.

**Comment by szh** [comment]
Fixed in #414
