### ISSUE TITLE
tar.gz files are not actually tar.gz files

### ISSUE THREAD

**Issue by The-Loeki** [cyberark/cyberark-conjur-cli#405]
## Steps to Reproduce
```
box:/tmp > curl -LO https://github.com/cyberark/cyberark-conjur-cli/releases/download/v7.1.0/conjur-cli-rhel-8.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   663  100   663    0     0   2602      0 --:--:-- --:--:-- --:--:--  2610
100 20.4M  100 20.4M    0     0  1355k      0  0:00:15  0:00:15 --:--:-- 1517k
box:/tmp > tar xzvf ./conjur-cli-rhel-8.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

box:/tmp > file ./conjur-cli-rhel-8.tar.gz 
./conjur-cli-rhel-8.tar.gz: POSIX tar archive (GNU)

box:/tmp > tar xvf ./conjur-cli-rhel-8.tar.gz 
conjur

```

## Expected Results
A gzipped tarfile

## Actual Results
A tarfile

## Additional Information
https://github.com/cyberark/cyberark-conjur-cli/blob/main/CONTRIBUTING.md#rhel-78

Outlines to use `tar cvf`  which in fact does not create a gzip'd archive; for that you need `z` added.

**Comment by szh** [comment]
Yes, this does look like a mistake. The [official docs](https://docs.conjur.org/Latest/en/Content/Developer/CLI/cli-setup.htm?tocpath=Developer%7CConjur%20CLI%7C_____1) actually list the command for extracting the file as `tar -xvf conjur-cli-<RHEL version>.tar.gz` without a `z`. We'll fix this in the next release and update the official docs when it's out.
